config/routes.rb
OotdApp::Application.routes.draw do

  get "users/new"
  get "static_pages/contact"
  get "static_pages/help"
  get "static_pages/about"

  root to: 'posts#index'
  
  resources :users

  resources :posts do
        member do
          get 'update_likes'
        end
  end
    

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/most_liked', to: 'posts#most_liked', via: :get
  match '/most_expensive', to: 'posts#most_expensive', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to: 'static_pages#contact', via: :get
  match '/help', to: 'static_pages#help', via: :get

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :content, presence: true
	validates :user_id, presence: true
	serialize :liked_users, Array
	has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_attached_file :image

  has_many :posts

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user,
                only: [:show, :update_likes, :most_liked, :most_expensive, :create, :destroy]
  def new
  	@new_post = Post.new
  end

  def index
  	@Posts = Post.all.order("posts.created_at desc")
  end

  def update_likes
  	@post = Post.find(params[:id])
    if !@post.liked_users.include?(current_user.name)
  	   @post.likes += 1
       @post.liked_users.push(current_user.name)
       @post.save
    end
  	redirect_to :back
  end

  def most_liked
    @Posts = Post.all.sort_by!{|post| post.likes}.reverse!
  end

  def most_expensive
    @Posts = Post.all.sort_by!{|post| post.price}.reverse!
  end

  def create
  	@post = Post.new(posts_params)
  	@post.likes = 0
    @post.user_id = current_user.id
  	if @post.save
  		redirect_to current_user
  	else
      flash[:error] = "#{@post.errors.full_messages}"
  		redirect_to :back
  	end
  end

  def destroy
  end

  private

  def posts_params
  	params.require(:post).permit(:price, :content, :image)
  end

  def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "Please sign in." 
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
  		if user && user.authenticate(params[:session][:password])
  			sign_in user
      	redirect_to posts_path
    		# Sign the user in and redirect to the user's show page.
  		else
   		 	flash[:error] = 'Invalid email/password combination'
        redirect_to :back
      end
	end

	def destroy
    	sign_out
  	  	redirect_to root_url
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :signed_in_user
  def contact
  end

  def help
  end

  def about
  end

  def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "Please sign in." 
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :show]
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to Outfit of the Day!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def index
  	@Users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :image, :password_confirmation)
  end

  def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "Please sign in." 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.encrypt(remember_token))
    	self.current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def sign_out
    	current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
  	end
  	
  	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	remember_token = User.encrypt(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def total_price(posts)
		total = 0
		posts.each do |post|
			total += post.price
		end
		return total
	end

	def average_price(posts)
		if posts.count == 0
			return 0
		end
		total = total_price(posts)
		return total/(posts.count)
	end

	def total_likes(posts)
		total = 0
		posts.each do |post|
			total += post.likes
		end
		return total
	end

	def average_likes(posts)
		if posts.count == 0
			return 0
		end
		total = total_likes(posts)
		return total/(posts.count)
	end
end

app/views/layouts/_static_pages.html.erb
<!DOCTYPE html>
<div style = "font-family: Courier New; text-align: center; margin-top: -22px; float: left; width: 101%; position: fixed; top: 0%; margin-left: -10px;">
<h1 style = "color: #9999FF; background: #CCFFFF">OOTD</h1>
<h3 style = "color: #CCFFFF; background: #9999FF; margin-top: -22px">Outfit of the Day</h3>
</div>



<%= yield %>


<div style = "background: #CCFFFF; height: 30px ; float: left; width: 101%; position: fixed; bottom: 0%; margin-left: -10px;">
<p style = "float:left; margin-left: 30px; margin-top: 6px; color: grey; font-size: 80%"> created by Katelynn Kyker </p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Contact", contact_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Help", help_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "About", about_path %></p>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OotdApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%=render 'shared/header'%>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style = "margin-top: 10%"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_sidebar.html.erb
<head>


<h1 style = "color: #9999FF; background: #CCFFFF; margin-top:9%;">
	<font style = "font-size: 50%; font-family: Tahoma; float: left; position: fixed; margin-top: 0px; margin-left: 20px"> <%= link_to "Create New Post", new_post_path %></font>
</h1>
<br></br>

<h1 style = "color: #9999FF; background: #CCFFFF">
	<font style = "font-size: 50%; font-family: Tahoma; float: left; position: fixed; margin-top: 0px; margin-left: 20px"> <%= link_to "Most Recent", root_url %></font>
</h1>
<br></br>
<h1 style = "color: #9999FF; background: #CCFFFF">
	<font style = "font-size: 50%; font-family: Tahoma; float: left; position: fixed; margin-top: -30px; margin-left: 20px"> <%= link_to "Most Liked", most_liked_path %></font>
</h1>
<br></br>
<h1 style = "color: #9999FF; background: #CCFFFF">
	<font style = "font-size: 50%; font-family: Tahoma; float: left; position: fixed; margin-top: -60px; margin-left: 20px"> <%= link_to "Most Expensive", most_expensive_path %></font>
</h1>

</head>

<center style = "color: #9999FF; font-family: Tahoma; font-weight: bold; font-size: 1em; margin-top: -16%">

</center>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<% if signed_in? %>

<%= render 'sidebar' %>

<center>
<% @Posts.each do |post| %>
<h3 style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.7em"><%= post.created_at.strftime("%B %e, %Y") %></h3>


<%= link_to image_tag(post.image.url, width: "300", style: "margin-left: 7%; border: 3px solid black"), user_path(post.user_id)%>



<%= link_to image_tag("/assets/like.png", width: "40px", style: "margin-top: -1%"), update_likes_post_path(post.id) %>
<font style = "font-weight: bold; font-size: 150%" > <%= post.likes %> </font>

<p style = "color: black; font-family: Tahoma; font-size: 80%; margin-top: 15px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Author: </font> <%= link_to User.find(post.user_id).name, user_path(post.user_id)%> 
	<font style = "font-weight: bold">Price: </font> $<%= post.price %> 
</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: -8px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Details: </font> <%= post.content %>
</p>
<br />
<% end %>
</center>




<% else %>

<h1 style = "font-family: Tahoma; margin-top: 12%">Welcome to OOTD</h1>
<font style= "font-family: Tahoma; margin-left: 6%; font-size: 1.4em"> <%= link_to "Sign up now", signup_path %> </font>

<img style = "margin-top: -1.7%; width: 12%; position: fixed" src="/assets/im.jpg" alt="im" >
<img style = "margin-top: -1.7%; margin-left: 20%; width: 12%; position: fixed" src="/assets/im2.jpg" alt="im2" >
<img style = "margin-top: -1.7%; margin-left: 40%; width: 12%; position: fixed" src="/assets/im4.jpg" alt="im4" >
<img style = "margin-top: -1.7%; margin-left: 60%; width: 12%; position: fixed" src="/assets/im3.jpg" alt="im3" >

<% end %>

app/views/posts/most_expensive.html.erb
<%= render 'sidebar' %>

<center>
<% @Posts.each do |post| %>
<h3 style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.7em"><%= post.created_at.strftime("%B %e, %Y") %></h3>


<%= link_to image_tag(post.image.url, width: "300", style: "margin-left: 7%; border: 3px solid black"), user_path(post.user_id)%>



<%= link_to image_tag("/assets/like.png", width: "40px", style: "margin-top: -1%"), update_likes_post_path(post.id) %>
<font style = "font-weight: bold; font-size: 150%" > <%= post.likes %> </font>

<p style = "color: black; font-family: Tahoma; font-size: 80%; margin-top: 15px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Author: </font> <%= link_to User.find(post.user_id).name, user_path(post.user_id)%> 
	<font style = "font-weight: bold">Price: </font> $<%= post.price %> 
</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: -8px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Details: </font> <%= post.content %>
</p>
<br />
<% end %>
</center>

app/views/posts/most_liked.html.erb
<%= render 'sidebar' %>

<center>
<% @Posts.each do |post| %>
<h3 style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.7em"><%= post.created_at.strftime("%B %e, %Y") %></h3>


<%= link_to image_tag(post.image.url, width: "300", style: "margin-left: 7%; border: 3px solid black"), user_path(post.user_id)%>



<%= link_to image_tag("/assets/like.png", width: "40px", style: "margin-top: -1%"), update_likes_post_path(post.id) %>
<font style = "font-weight: bold; font-size: 150%" > <%= post.likes %> </font>

<p style = "color: black; font-family: Tahoma; font-size: 80%; margin-top: 15px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Author: </font> <%= link_to User.find(post.user_id).name, user_path(post.user_id)%> 
	<font style = "font-weight: bold">Price: </font> $<%= post.price %> 
</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: -8px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Details: </font> <%= post.content %>
</p>
<br />
<% end %>
</center>

app/views/posts/new.html.erb
<center style = "margin-top: 100px; color: black; font-family: Tahoma; font-weight: bold; font-size: 1em;">
<%= form_for @new_post, :html => { :multipart => true} do |f| %>
Author: <font style = "font-weight: normal"> <%= current_user.name %> </font> <br />
<br />
Price: $<%= f.text_field :price, :size => 5 %> <br />
<br/>
Details: <%= f.text_area :content, :rows => 5%> <br />
<br />
<h4>Upload your outfit</h4>
<%= f.file_field :image %>

<%= f.submit "Create Post", class: "btn btn-normal btn-primary" %>
<% end %>
</center>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div style = "background: #ADD8E6; font-family: Tahoma; height: 30px ; float: left; width: 102%; position: fixed; bottom: 0%; margin-left: -20px;">
<p style = "float:left; margin-left: 30px; margin-top: 6px; color: grey; font-size: 80%"> created by Katelynn Kyker </p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Contact", contact_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Help", help_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "About", about_path %></p>
</div>

app/views/shared/_header.html.erb
<div style = "position: fixed; width: 100%; margin-top: -4%">

<h1 style = "color: #9999FF; margin-top: 2%; background: #ADD8E6; padding-top: 8px; padding-bottom: 8px; margin-bottom: 0px">
	
	<% if signed_in? %>

	<font style = "font-size: 50%; font-family: Tahoma; float: right; margin-right: 40px"> <%= link_to "Sign Out", signout_path, method: "delete" %></font>

	<font style = "font-size: 50%; font-family: Tahoma; float: right;margin-right: 40px"> <%= link_to "Users", users_path %></font>
	
	<font style = "font-family: Tahoma; font-size: 140%; text-align: center;"> <%= link_to "OOTD", root_url %></font>

	<font style = "font-size: 50%; font-family: Tahoma; float: left; width: 40.3%; margin-left: 40px"> <%= link_to current_user.name, user_path(current_user.id) %></font>
	
	<% else %>
	
	<font style = "font-size: 50%; font-family: Tahoma; float: right; margin-right: 40px"> <%= link_to "Sign in", signin_path %></font>

	<font style = "font-size: 140%; font-family: Tahoma; text-align: center; margin-left: 43.5%"> <%= link_to "OOTD", root_url %></font>
	 
	<% end %>

	

</h1>

<h3 style = "color: #ADD8E6; background: rgb(72, 156, 223); margin-top: 0px; font-size: 130%; text-align: center">Outfit of the Day</h3>
</div>

<br />
<br />

app/views/static_pages/about.html.erb
<!DOCTYPE html>



<p style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.4em; margin-top: 100px; text-align: center">What is OOTD?</p>

<center>
<img style = "border: 3px solid black; margin-top: -10px" align = "middle" src="/assets/ootd2.jpg" alt="ootd" width="200" >
</center>

<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%">OOTD stands for Outfit of the Day. This website enables people interested in fashion to share their daily looks with each other. OOTD's inspiration came from fashion gurus on YouTube that make videos about their daily looks. Enjoy!</p>

<p style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.4em; margin-top: 10px; text-align: center">Who am I?</p>

<center>
<img style = "border: 3px solid black; margin-top: -10px" align = "middle" src="/assets/kyker.jpg" alt="ootd" width="200" >
</center>

<center>
<a href="http://we-need-an-escape.tumblr.com" style = "color: black; font-family: Tahoma; margin-top: -10 px">
My personal blog</a>
</center>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%; margin-bottom: 35px">I am 17 years old and new to coding. This is my first website. Although I am not very into fashion, many of my friends are fashion geeks, which is why I decided to build this website. Maybe your photos will inspire me.</p>






<div style = "background: #CCFFFF; font-family: Tahoma; height: 30px ; float: left; width: 101%; position: fixed; bottom: 0%; margin-left: -10px;">
<p style = "float:left; margin-left: 30px; margin-top: 6px; color: grey; font-size: 80%"> created by Katelynn Kyker </p>

<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Contact", contact_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Help", help_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "About", about_path %></p>
</div>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>


<p style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1 em; margin-top: 200px; margin-left: 30%; margin-right: 30%">If you need help with tech issues, email me at kkyker17@gmail.com. However, I can't help you with the fashion or your outfits. You're on your own for that.</p>



<div style = "background: #CCFFFF; font-family: Tahoma; height: 30px ; float: left; width: 101%; position: fixed; bottom: 0%; margin-left: -10px;">
<p style = "float:left; margin-left: 30px; margin-top: 6px; color: grey; font-size: 80%"> created by Katelynn Kyker </p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Contact", contact_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Help", help_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "About", about_path %></p>
</div>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>



<p style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.4em; margin-top: 100px; text-align: center">How to Use OOTD</p>


<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%">1. Sign up!</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%">2. Post a picture by uploading an image from your computer. Add the price and details of your outfit.</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%">3. View other users' outfits on the main OOTD page. You can sort through all the looks by price, date posted, or favorites.</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: 20px; margin-left: 30%; margin-right: 30%">4. Favorite the outfits you like by clicking on the purple star.</p>


<div style = "background: #CCFFFF; height: 30px ; font-family: Tahoma; float: left; width: 101%; position: fixed; bottom: 0%; margin-left: -10px;">
<p style = "float:left; margin-left: 30px; margin-top: 6px; color: grey; font-size: 80%"> created by Katelynn Kyker </p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Contact", contact_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "Help", help_path %></p>
<p style = "float: right; margin-right: 40px; margin-top: 5px"><%= link_to "About", about_path %></p>
</div>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>




<h2 style = "font-family: Tahoma; margin-top: 100px; margin-left: 15px; margin-bottom: 20px">OOTD Users (<%= @Users.count %>)</h2>


<img style = "margin-top: -13%; margin-left: 50%; width: 16%; position: fixed" src="/assets/im5.jpg" alt="im5">
<img style = "margin-top: -14%; margin-left: 70%; width: 16%; position: fixed" src="/assets/im6.jpg" alt="im6">

<body style = "font-family: Tahoma">

<ul style = "list-style: none">

	<% @Users.each do |user| %>
	<li>
		<h3> <%= link_to user.name, user %></h3>
		<p style = "margin-left: 25px">Number of Posts: <%= user.posts.count%></p>
		<p style = "margin-left: 25px">Total Money Spent: <%= total_price(user.posts)%></p>
		<p style = "margin-left: 25px">Average Price of Outfit <%= average_price(user.posts)%></p>
		<p style = "margin-left: 25px">Total Likes: <%= total_likes(user.posts)%></p>
		<p style = "margin-left: 25px">Average Likes per Outfit: <%= average_likes(user.posts)%></p>
	</li>
	<% end %>
	<br />
>
<ul>
</body>


</html>

app/views/users/new.html.erb
<br />
<br />
<br />
<br />
<br />
<br />
<center>
<img style = "margin-top: -9.1%; position: fixed" align = "middle" src="/assets/burb1.jpg" alt="burb1" width="800" >



<font style= "font-family: Tahoma">
<div class="row" style = "margin-left: 8%; position: fixed">
  <div class="span6 offset3">
    <h3 style = "margin-bottom: 3px;">Sign Up</h3>
    <%= form_for(@user,:html => { :multipart => true}) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.text_field :name, :placeholder => "Name" %>
      <br />

      <%= f.text_field :email, :placeholder => "Email"  %>
      <br />

      <%= f.password_field :password, :placeholder => "Password"  %>
      <br />

      <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation"  %>
      <br />
      <h5 style = "margin-bottom: 0px">Select profile picture</h5>
      <%= f.file_field :image, style: "margin-left: 90px; margin-bottom: 10px" %>

      <%= f.submit "Create my account", class: "btn btn-normal btn-primary" %>
    <% end %>
  </div>
</div>
</font>
</center>

app/views/users/show.html.erb
<center style = "color: #9999FF; font-family: Tahoma; font-weight: bold; font-size: 1em; margin-top: 70px">

<br />

</center>

<%= image_tag(@user.image.url, width: "80", style: "border: 1px solid black; float: left; margin-right: 20px; margin-top: 10px")%>

<h1 style= "font-family: Tahoma"><%= @user.name %></h1>
<h3 style= "font-family: Tahoma">Outfits (<%=@user.posts.count%>)</h3>

<% if @user.id == current_user.id %>
<%= link_to "Create New Post", new_post_path(params[:id]) %>
<% end %>

<center>
<% @user.posts.each do |post| %>
<h3 style = "color: black; font-family: Tahoma; font-weight: bold; font-size: 1.7em"><%= post.created_at.strftime("%B %e, %Y") %></h3>


<%= link_to image_tag(post.image.url, width: "300", style: "margin-left: 7%; border: 3px solid black"), user_path(post.user_id)%>



<%= link_to image_tag("/assets/like.png", width: "40px", style: "margin-top: -1%"), update_likes_post_path(post.id) %>
<font style = "font-weight: bold; font-size: 150%" > <%= post.likes %> </font>

<p style = "color: black; font-family: Tahoma; font-size: 80%; margin-top: 15px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Author: </font> <%= link_to User.find(post.user_id).name, user_path(post.user_id)%> 
	<font style = "font-weight: bold">Price: </font> $<%= post.price %> 
</p>
<p style = "color: black; font-family: Tahoma; font-size: 1 em; margin-top: -8px; margin-left: 30%; margin-right: 30%">
	<font style = "font-weight: bold">Details: </font> <%= post.content %>
</p>
<br />
<% end %>
</center>